apiVersion: v1
kind: ReplicationController
metadata:
  name: "elasticsearch-logging-client"
spec:
  replicas: 3
  selector:
    component: "elasticsearch-logging"
    type: "client"
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "Always",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
      labels:
        component: "elasticsearch-logging"
        type: "client"
    spec:
      serviceAccount: elasticsearch-logging
      serviceAccountName: elasticsearch-logging
      containers:
      - name: "elasticsearch-logging"
        env:
        - name: "SERVICE"
          value: "elasticsearch-logging-cluster"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "CLUSTER_NAME"
          value: "logging"
        - name: "NODE_DATA"
          value: "false"
        - name: "NODE_MASTER"
          value: "false"
        - name: "NUMBER_OF_MASTERS"
          value: "3"
        - name: "ES_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        image: "elasticsearch-logging:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 9200
            name: "http"
          - containerPort: 9300
            name: "transport"
