apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch-logging"
spec:
  type: "NodePort"
  ports:
  - port: 9200
    targetPort: "http"
  selector:
    component: "elasticsearch-logging"
    type: "client"
