apiVersion: v1
kind: Service
metadata:
  name: "elasticsearch-logging-cluster"
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    component: "elasticsearch-logging"
