apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "elasticsearch-logging-data"
spec:
  serviceName: "elasticsearch-logging-data"
  replicas: 3
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "Always",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
      labels:
        component: "elasticsearch-logging"
        type: "data"
    spec:
      serviceAccount: elasticsearch-logging
      serviceAccountName: elasticsearch-logging
      nodeSelector:
        cloud.google.com/gke-nodepool: "logging-1-5-1"
      containers:
        - name: "elasticsearch-logging"
          env:
          - name: "SERVICE"
            value: "elasticsearch-logging-cluster"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "CLUSTER_NAME"
            value: "logging"
          - name: "NODE_DATA"
            value: "true"
          - name: "NODE_MASTER"
            value: "false"
          - name: "NUMBER_OF_MASTERS"
            value: "3"
          - name: "ES_JAVA_OPTS"
            value: "-Xms4g -Xmx4g"
          image: "elasticsearch-logging:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 9300
              name: "transport"
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elasticsearch-data

  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: "10Gi"
