apiVersion: v1
kind: ReplicationController
metadata:
  name: "elasticsearch-logging-kibana"
spec:
  replicas: 1
  selector:
    component: "elasticsearch-logging-kibana"
  template:
    metadata:
      labels:
        component: "elasticsearch-logging-kibana"
    spec:
      containers:
      - name: "elasticsearch-logging-kibana"
        env:
        - name: "ELASTICSEARCH_URL"
          value: "http://elasticsearch-logging:9200"
          image: "kibana:5.1.1"
        imagePullPolicy: Always
        ports:
          - containerPort: 5601
            name: "http"
