apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch-logging-kibana"
spec:
  # type: "LoadBalancer"
  type: "NodePort"
  ports:
  - port: 5601
    targetPort: "http"
  selector:
    component: "elasticsearch-logging-kibana"